@extends('layouts.admin')

@section('title', 'Assessments & Goals')

@section('content')
    <div class="d-flex justify-content-between align-items-center mb-4"><div><p class="page-title mb-1">Assessments &amp; Goals</p><p class="page-subtitle mb-0">Track patient evaluation progress, scores, and treatment goals.</p></div></div>
    <div class="card shadow-sm mb-4 border-0"><div class="card-header"><h5 class="mb-0">Add assessment</h5></div><div class="card-body"><form method="post" action="{{ url('/assessments/save') }}">@csrf<div class="row g-3"><div class="col-md-3"><label class="form-label small fw-semibold">Patient</label><input type="text" name="patient" class="form-control" placeholder="Patient name" required></div><div class="col-md-3"><label class="form-label small fw-semibold">Therapist</label><input type="text" name="therapist" class="form-control" placeholder="Therapist name" required></div><div class="col-md-2"><label class="form-label small fw-semibold">Type</label><input type="text" name="type" class="form-control" placeholder="Mobility" required></div><div class="col-md-2"><label class="form-label small fw-semibold">Score</label><input type="text" name="score" class="form-control" placeholder="82%" required></div><div class="col-md-2"><label class="form-label small fw-semibold">Date</label><input type="date" name="date" class="form-control" required></div><div class="col-12"><label class="form-label small fw-semibold">Goal</label><textarea name="goal" class="form-control" rows="3" placeholder="Describe the treatment goal..." required></textarea></div><div class="col-12 text-end"><button type="submit" class="btn btn-primary">Save assessment</button></div></div></form></div></div>
    <div class="row g-4 mb-4"><div class="col-md-6 col-xl-4"><div class="card stat-card h-100 border-0"><div class="d-flex justify-content-between align-items-center"><div><div class="stat-label">Average score</div><h4 class="stat-value mb-0">{{ $averageScore }}</h4></div><i class="bi bi-bar-chart stat-icon text-primary"></i></div></div></div><div class="col-md-6 col-xl-4"><div class="card stat-card h-100 border-0"><div class="d-flex justify-content-between align-items-center"><div><div class="stat-label">Goal tracking</div><h4 class="stat-value mb-0">{{ $goalTracking }}</h4></div><i class="bi bi-bullseye stat-icon text-success"></i></div></div></div><div class="col-md-6 col-xl-4"><div class="card stat-card h-100 border-0"><div class="d-flex justify-content-between align-items-center"><div><div class="stat-label">Active patients</div><h4 class="stat-value mb-0">{{ $activePatients }}</h4></div><i class="bi bi-people stat-icon text-info"></i></div></div></div></div>
    <div class="card shadow-sm border-0"><div class="card-header"><h5 class="mb-0">Latest assessments</h5></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0 align-middle"><thead class="table-light"><tr><th>Patient</th><th>Therapist</th><th>Type</th><th>Score</th><th>Goal</th><th>Date</th></tr></thead><tbody>@forelse ($assessments as $entry)<tr><td>{{ $entry['patient'] }}</td><td>{{ $entry['therapist'] }}</td><td>{{ $entry['type'] }}</td><td>{{ $entry['score'] }}</td><td>{{ $entry['goal'] }}</td><td>{{ $entry['date'] }}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">No assessments available.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
