@extends('layouts.admin')

@section('title', 'Therapy Notes & Care Plans')

@section('content')
    <div class="d-flex justify-content-between align-items-center mb-4"><div><p class="page-title mb-1">Therapy Notes &amp; Care Plans</p><p class="page-subtitle mb-0">Track patient progress, therapist notes, and treatment plans.</p></div></div>
    <div class="card shadow-sm mb-4 border-0"><div class="card-header"><h5 class="mb-0">Add therapy note</h5></div><div class="card-body"><form method="post" action="{{ url('/notes/save') }}">@csrf<div class="row g-3"><div class="col-md-3"><label class="form-label small fw-semibold">Patient</label><input type="text" name="patient" class="form-control" placeholder="Patient name" required></div><div class="col-md-3"><label class="form-label small fw-semibold">Therapist</label><input type="text" name="therapist" class="form-control" placeholder="Therapist name" required></div><div class="col-md-3"><label class="form-label small fw-semibold">Topic</label><input type="text" name="topic" class="form-control" placeholder="Mobility progress" required></div><div class="col-md-3"><label class="form-label small fw-semibold">Date</label><input type="date" name="date" class="form-control" required></div><div class="col-12"><label class="form-label small fw-semibold">Care plan / note</label><textarea name="note" class="form-control" rows="4" placeholder="Write the patient progress note here..." required></textarea></div><div class="col-12 text-end"><button type="submit" class="btn btn-primary">Save note</button></div></div></form></div></div>
    <div class="row g-4 mb-4"><div class="col-md-6"><div class="card stat-card h-100 border-0"><div class="d-flex justify-content-between align-items-center"><div><div class="stat-label">Recent entries</div><h4 class="stat-value mb-0">{{ $recentCount }}</h4></div><i class="bi bi-journal-check stat-icon text-primary"></i></div></div></div><div class="col-md-6"><div class="card stat-card h-100 border-0"><div class="d-flex justify-content-between align-items-center"><div><div class="stat-label">Today notes</div><h4 class="stat-value mb-0">{{ $todayNotes }}</h4></div><i class="bi bi-calendar-event stat-icon text-success"></i></div></div></div></div>
    <div class="card shadow-sm border-0"><div class="card-header"><h5 class="mb-0">Latest care plan notes</h5></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0 align-middle"><thead class="table-light"><tr><th>Patient</th><th>Therapist</th><th>Topic</th><th>Note</th><th>Date</th></tr></thead><tbody>@forelse ($notes as $entry)<tr><td>{{ $entry['patient'] }}</td><td>{{ $entry['therapist'] }}</td><td>{{ $entry['topic'] }}</td><td>{{ $entry['note'] }}</td><td>{{ $entry['date'] }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">No care plan notes available.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
